#!/usr/bin/env python3
"""
GGWP — GlyphSheet Generation Workflow Protocol
Build TrueType fonts from filled glyph sheet SVGs.

Usage:
    python3 build_fonts.py                       # uses sheet_config.py
    python3 build_fonts.py my_config.py          # uses custom config
    python3 build_fonts.py my_config.py Bold     # build only Bold weight

The config file must define a CONFIG dict. See sheet_config.py for format.
The SVG sheets must have been generated by generate_sheet.py and filled
with glyph paths by the designer.

Dependencies:
    pip install fonttools
"""

import sys
import os
import re
import math
import xml.etree.ElementTree as ET
import importlib.util

from fontTools.fontBuilder import FontBuilder
from fontTools.pens.ttGlyphPen import TTGlyphPen
from fontTools.pens.cu2quPen import Cu2QuPen
from fontTools.ttLib.tables.O_S_2f_2 import Panose


NS = {"svg": "http://www.w3.org/2000/svg"}


# ---------------------------------------------------------------------------
# Config loader (shared with generate_sheet.py)
# ---------------------------------------------------------------------------


def load_config(config_path):
    """Load CONFIG dict from a Python file."""
    spec = importlib.util.spec_from_file_location("config_module", config_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, "CONFIG"):
        raise ValueError(f"{config_path} does not define a CONFIG dict")
    return mod.CONFIG


# ---------------------------------------------------------------------------
# SVG path tokenizer / transformer
# ---------------------------------------------------------------------------


def _tokenize_path(d):
    """Yield (cmd, [args]) tuples from an SVG path d string."""
    token_re = re.compile(
        r"([MmZzLlHhVvCcSsQqTtAa])|([+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?)"
    )
    tokens = token_re.findall(d)
    cmd = None
    args = []
    for cmd_tok, num_tok in tokens:
        if cmd_tok:
            if cmd is not None:
                yield cmd, args
            cmd = cmd_tok
            args = []
        elif num_tok:
            args.append(float(num_tok))
    if cmd is not None:
        yield cmd, args


def _chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i : i + n]


def _arc_to_bezier(pen, x1, y1, rx, ry, phi, large_arc, sweep, x2, y2, tx):
    """Convert SVG arc to cubic bezier curves and draw to pen."""
    if x1 == x2 and y1 == y2:
        return
    if rx == 0 or ry == 0:
        pen.lineTo(tx(x2, y2))
        return

    phi_rad = math.radians(phi)
    cos_phi = math.cos(phi_rad)
    sin_phi = math.sin(phi_rad)

    dx = (x1 - x2) / 2
    dy = (y1 - y2) / 2
    x1p = cos_phi * dx + sin_phi * dy
    y1p = -sin_phi * dx + cos_phi * dy

    rx = abs(rx)
    ry = abs(ry)
    x1p_sq = x1p * x1p
    y1p_sq = y1p * y1p
    rx_sq = rx * rx
    ry_sq = ry * ry

    lam = x1p_sq / rx_sq + y1p_sq / ry_sq
    if lam > 1:
        s = math.sqrt(lam)
        rx *= s
        ry *= s
        rx_sq = rx * rx
        ry_sq = ry * ry

    num = max(0, rx_sq * ry_sq - rx_sq * y1p_sq - ry_sq * x1p_sq)
    den = rx_sq * y1p_sq + ry_sq * x1p_sq
    sq = math.sqrt(num / den) if den != 0 else 0
    if large_arc == sweep:
        sq = -sq

    cxp = sq * rx * y1p / ry
    cyp = -sq * ry * x1p / rx

    cx = cos_phi * cxp - sin_phi * cyp + (x1 + x2) / 2
    cy = sin_phi * cxp + cos_phi * cyp + (y1 + y2) / 2

    def angle(ux, uy, vx, vy):
        n = math.sqrt(ux * ux + uy * uy) * math.sqrt(vx * vx + vy * vy)
        if n == 0:
            return 0
        c = max(-1, min(1, (ux * vx + uy * vy) / n))
        a = math.acos(c)
        if ux * vy - uy * vx < 0:
            a = -a
        return a

    theta1 = angle(1, 0, (x1p - cxp) / rx, (y1p - cyp) / ry)
    dtheta = angle(
        (x1p - cxp) / rx, (y1p - cyp) / ry, (-x1p - cxp) / rx, (-y1p - cyp) / ry
    )

    if not sweep and dtheta > 0:
        dtheta -= 2 * math.pi
    elif sweep and dtheta < 0:
        dtheta += 2 * math.pi

    n_segs = max(1, math.ceil(abs(dtheta) / (math.pi / 2)))
    d_theta_per = dtheta / n_segs
    alpha = 4 / 3 * math.tan(d_theta_per / 4)

    theta = theta1
    for _ in range(n_segs):
        cos_t = math.cos(theta)
        sin_t = math.sin(theta)
        cos_t2 = math.cos(theta + d_theta_per)
        sin_t2 = math.sin(theta + d_theta_per)

        p1x = cx + cos_phi * (rx * cos_t) - sin_phi * (ry * sin_t)
        p1y = cy + sin_phi * (rx * cos_t) + cos_phi * (ry * sin_t)
        d1x = cos_phi * (-rx * sin_t) - sin_phi * (ry * cos_t)
        d1y = sin_phi * (-rx * sin_t) + cos_phi * (ry * cos_t)
        p2x = cx + cos_phi * (rx * cos_t2) - sin_phi * (ry * sin_t2)
        p2y = cy + sin_phi * (rx * cos_t2) + cos_phi * (ry * sin_t2)
        d2x = cos_phi * (-rx * sin_t2) - sin_phi * (ry * cos_t2)
        d2y = sin_phi * (-rx * sin_t2) + cos_phi * (ry * cos_t2)

        cp1x = p1x + alpha * d1x
        cp1y = p1y + alpha * d1y
        cp2x = p2x - alpha * d2x
        cp2y = p2y - alpha * d2y

        pen.curveTo(tx(cp1x, cp1y), tx(cp2x, cp2y), tx(p2x, p2y))
        theta += d_theta_per


def draw_svg_path_to_pen(d, pen, transform=None):
    """Parse SVG path d and draw to a fontTools pen."""

    def tx(x, y):
        if transform is None:
            return x, y
        sx, shy, shx, sy, dx, dy = transform
        return sx * x + shx * y + dx, shy * x + sy * y + dy

    cx, cy = 0.0, 0.0
    sx, sy_ = 0.0, 0.0
    last_ctrl = None
    in_contour = False

    def close_if_open():
        nonlocal in_contour
        if in_contour:
            pen.endPath()
            in_contour = False

    for cmd, args in _tokenize_path(d):
        if cmd == "M":
            close_if_open()
            pts = list(_chunks(args, 2))
            first = pts[0]
            cx, cy = first
            sx, sy_ = cx, cy
            pen.moveTo(tx(cx, cy))
            in_contour = True
            last_ctrl = None
            for p in pts[1:]:
                cx, cy = p
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "m":
            close_if_open()
            pts = list(_chunks(args, 2))
            first = pts[0]
            cx += first[0]
            cy += first[1]
            sx, sy_ = cx, cy
            pen.moveTo(tx(cx, cy))
            in_contour = True
            last_ctrl = None
            for p in pts[1:]:
                cx += p[0]
                cy += p[1]
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd in ("Z", "z"):
            if in_contour:
                pen.closePath()
                in_contour = False
            cx, cy = sx, sy_
            last_ctrl = None

        elif cmd == "L":
            for p in _chunks(args, 2):
                cx, cy = p
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "l":
            for p in _chunks(args, 2):
                cx += p[0]
                cy += p[1]
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "H":
            for x in args:
                cx = x
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "h":
            for x in args:
                cx += x
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "V":
            for y in args:
                cy = y
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "v":
            for y in args:
                cy += y
                pen.lineTo(tx(cx, cy))
                last_ctrl = None

        elif cmd == "C":
            for chunk in _chunks(args, 6):
                x1, y1, x2, y2, x, y = chunk
                pen.curveTo(tx(x1, y1), tx(x2, y2), tx(x, y))
                last_ctrl = (x2, y2)
                cx, cy = x, y

        elif cmd == "c":
            for chunk in _chunks(args, 6):
                x1, y1, x2, y2, x, y = chunk
                ax1, ay1 = cx + x1, cy + y1
                ax2, ay2 = cx + x2, cy + y2
                ax, ay = cx + x, cy + y
                pen.curveTo(tx(ax1, ay1), tx(ax2, ay2), tx(ax, ay))
                last_ctrl = (ax2, ay2)
                cx, cy = ax, ay

        elif cmd == "S":
            for chunk in _chunks(args, 4):
                x2, y2, x, y = chunk
                if last_ctrl is not None:
                    x1 = 2 * cx - last_ctrl[0]
                    y1 = 2 * cy - last_ctrl[1]
                else:
                    x1, y1 = cx, cy
                pen.curveTo(tx(x1, y1), tx(x2, y2), tx(x, y))
                last_ctrl = (x2, y2)
                cx, cy = x, y

        elif cmd == "s":
            for chunk in _chunks(args, 4):
                x2, y2, x, y = chunk
                ax2, ay2 = cx + x2, cy + y2
                ax, ay = cx + x, cy + y
                if last_ctrl is not None:
                    ax1 = 2 * cx - last_ctrl[0]
                    ay1 = 2 * cy - last_ctrl[1]
                else:
                    ax1, ay1 = cx, cy
                pen.curveTo(tx(ax1, ay1), tx(ax2, ay2), tx(ax, ay))
                last_ctrl = (ax2, ay2)
                cx, cy = ax, ay

        elif cmd == "Q":
            for chunk in _chunks(args, 4):
                x1, y1, x, y = chunk
                pen.qCurveTo(tx(x1, y1), tx(x, y))
                last_ctrl = (x1, y1)
                cx, cy = x, y

        elif cmd == "q":
            for chunk in _chunks(args, 4):
                x1, y1, x, y = chunk
                ax1, ay1 = cx + x1, cy + y1
                ax, ay = cx + x, cy + y
                pen.qCurveTo(tx(ax1, ay1), tx(ax, ay))
                last_ctrl = (ax1, ay1)
                cx, cy = ax, ay

        elif cmd == "T":
            for p in _chunks(args, 2):
                x, y = p
                if last_ctrl is not None:
                    x1 = 2 * cx - last_ctrl[0]
                    y1 = 2 * cy - last_ctrl[1]
                else:
                    x1, y1 = cx, cy
                pen.qCurveTo(tx(x1, y1), tx(x, y))
                last_ctrl = (x1, y1)
                cx, cy = x, y

        elif cmd == "t":
            for p in _chunks(args, 2):
                ax, ay = cx + p[0], cy + p[1]
                if last_ctrl is not None:
                    ax1 = 2 * cx - last_ctrl[0]
                    ay1 = 2 * cy - last_ctrl[1]
                else:
                    ax1, ay1 = cx, cy
                pen.qCurveTo(tx(ax1, ay1), tx(ax, ay))
                last_ctrl = (ax1, ay1)
                cx, cy = ax, ay

        elif cmd in ("A", "a"):
            relative = cmd == "a"
            for chunk in _chunks(args, 7):
                rx, ry, x_rot, large, sweep, x, y = chunk
                if relative:
                    x, y = cx + x, cy + y
                _arc_to_bezier(
                    pen, cx, cy, rx, ry, x_rot, int(large), int(sweep), x, y, tx
                )
                last_ctrl = None
                cx, cy = x, y

    if in_contour:
        pen.endPath()


def draw_rect_to_pen(x, y, w, h, pen, transform=None):
    """Draw a rectangle as a closed contour."""

    def tx(px, py):
        if transform is None:
            return px, py
        sx, shy, shx, sy, dx, dy = transform
        return sx * px + shx * py + dx, shy * px + sy * py + dy

    pen.moveTo(tx(x, y))
    pen.lineTo(tx(x + w, y))
    pen.lineTo(tx(x + w, y + h))
    pen.lineTo(tx(x, y + h))
    pen.closePath()


# ---------------------------------------------------------------------------
# SVG reference line reader
# ---------------------------------------------------------------------------


def _normalize_color(color_str):
    """
    Normalize a color string to lowercase hex (#rrggbb).
    Handles: #hex, rgb(r,g,b), and inline style containing stroke:rgb().
    """
    if not color_str:
        return ""
    s = color_str.strip().lower()

    m = re.search(r"rgb\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*\)", s)
    if m:
        r, g, b = int(m.group(1)), int(m.group(2)), int(m.group(3))
        return f"#{r:02x}{g:02x}{b:02x}"

    if s.startswith("#"):
        return s

    return s


def _get_stroke_color(elem):
    """
    Extract stroke color from an SVG element.
    Checks both stroke= attribute and style= inline style.
    Returns normalized hex color string.
    """
    stroke = elem.get("stroke", "")
    if stroke:
        return _normalize_color(stroke)

    style = elem.get("style", "")
    if "stroke" in style:
        return _normalize_color(style)

    return ""


def read_reference_lines(svg_path, config):
    """
    Read reference line Y positions from the SVG by matching line colors.
    Returns dict: {"capline": y, "xheight": y, "baseline": y, "descender": y}
    Only reads from the first row (row 0) for consistency.
    """
    tree = ET.parse(svg_path)
    root = tree.getroot()

    ref_colors = {}
    for key, ref in config["reference_lines"].items():
        ref_colors[_normalize_color(ref["color"])] = key

    grid = config["grid"]
    margin_t = grid["margin_top"]
    label_h = grid.get("label_height", 0)
    cell_h = grid["cell_height"]

    # first cell drawing area bounds (row 0)
    dy0 = margin_t
    dy1 = margin_t + cell_h + label_h + 10  # generous bounds

    results = {}
    for elem in root.iter():
        tag = elem.tag.split("}")[-1]

        if tag == "line":
            stroke = _get_stroke_color(elem)
            if not stroke or stroke not in ref_colors:
                continue

            y1 = float(elem.get("y1", "0"))
            y2 = float(elem.get("y2", "0"))

            if abs(y1 - y2) > 0.5:
                continue
            if y1 < dy0 - 1 or y1 > dy1 + 1:
                continue

            key = ref_colors[stroke]
            if key not in results:
                results[key] = y1

        elif tag == "path":
            # Affinity exports lines as path: M x1,y1 L x2,y2
            stroke = _get_stroke_color(elem)
            if not stroke or stroke not in ref_colors:
                continue

            d = elem.get("d", "")
            m = re.match(
                r"M\s*([+-]?[\d.]+)\s*[,\s]\s*([+-]?[\d.]+)\s*"
                r"L\s*([+-]?[\d.]+)\s*[,\s]\s*([+-]?[\d.]+)\s*$",
                d.strip(),
            )
            if not m:
                continue

            y1 = float(m.group(2))
            y2 = float(m.group(4))

            if abs(y1 - y2) > 0.5:
                continue
            if y1 < dy0 - 1 or y1 > dy1 + 1:
                continue

            key = ref_colors[stroke]
            if key not in results:
                results[key] = y1

    return results


def read_sidebearing_markers(svg_path, config, col, row):
    """
    Read LSB/RSB marker X positions for a specific cell.
    Returns (lsb_x, rsb_x) or (None, None) if not found.
    """
    sb = config.get("sidebearing_markers", {})
    lsb_color = _normalize_color(sb.get("lsb_color", "#00FFFF"))
    rsb_color = _normalize_color(sb.get("rsb_color", "#FF00FF"))

    grid = config["grid"]
    margin_l = grid["margin_left"]
    margin_t = grid["margin_top"]
    label_h = grid.get("label_height", 0)
    cell_w = grid["cell_width"]
    cell_h = grid["cell_height"]
    col_gap = grid["col_gap"]
    row_gap = grid["row_gap"]
    col_step = cell_w + col_gap
    row_step = cell_h + row_gap + label_h

    cell_x = margin_l + col * col_step
    cell_dy = margin_t + row * row_step + label_h

    tree = ET.parse(svg_path)
    root = tree.getroot()

    lsb_x = None
    rsb_x = None

    for elem in root.iter():
        tag = elem.tag.split("}")[-1]
        if tag != "line":
            continue

        stroke = _get_stroke_color(elem)
        if stroke not in (lsb_color, rsb_color):
            continue

        x1 = float(elem.get("x1", "0"))
        y1 = float(elem.get("y1", "0"))
        x2 = float(elem.get("x2", "0"))
        y2 = float(elem.get("y2", "0"))

        # vertical line check (x1 == x2) within cell bounds
        if abs(x1 - x2) > 0.5:
            continue
        if y1 < cell_dy - 1 or y2 > cell_dy + cell_h + 1:
            continue
        if x1 < cell_x - 1 or x1 > cell_x + cell_w + 1:
            continue

        if stroke == lsb_color:
            lsb_x = x1
        elif stroke == rsb_color:
            rsb_x = x1

    return lsb_x, rsb_x


# ---------------------------------------------------------------------------
# Parse SVG sheet into glyph data
# ---------------------------------------------------------------------------


def parse_svg(svg_path, config):
    """
    Parse a filled glyph sheet SVG.
    Returns:
        glyphs: dict char -> list of (kind, data)
        char_grid: dict char -> (col, row)
    """
    tree = ET.parse(svg_path)
    root = tree.getroot()

    grid = config["grid"]
    columns = grid["columns"]
    cell_w = grid["cell_width"]
    cell_h = grid["cell_height"]
    col_gap = grid["col_gap"]
    row_gap = grid["row_gap"]
    label_h = grid["label_height"]
    margin_l = grid["margin_left"]
    margin_t = grid["margin_top"]
    col_step = cell_w + col_gap
    row_step = cell_h + row_gap + label_h

    label_font_size = config.get("appearance", {}).get("label_font_size", 7)

    # label position for col 0, row 0
    label_x0 = margin_l + 2
    label_y0 = margin_t + label_h - 3

    # find text labels to build grid mapping
    children = list(root)
    char_grid = {}
    glyphs = {}

    for i, child in enumerate(children):
        tag = child.tag.split("}")[-1]
        if tag != "text":
            continue

        style = child.get("style", "")
        if f"font-size:{label_font_size}px" not in style or not child.text:
            continue

        ch = child.text
        # unescape XML entities
        if ch.startswith("U+") and len(ch) >= 6:
            # U+XXXX format — skip, this is a non-printable label
            try:
                cp = int(ch[2:], 16)
                ch = chr(cp)
            except ValueError:
                continue

        lx = float(child.get("x", "0").replace("px", ""))
        ly = float(child.get("y", "0").replace("px", ""))

        col = round((lx - label_x0) / col_step)
        row = round((ly - label_y0) / row_step)

        if col < 0 or row < 0:
            continue

        char_grid[ch] = (col, row)

        # cell bounding box (generous margin for stray path filtering)
        cell_x0 = margin_l + col * col_step - col_step * 0.1
        cell_x1 = margin_l + col * col_step + col_step * 1.1
        cell_dy = margin_t + row * row_step + label_h
        cell_y0 = cell_dy - row_step * 0.1
        cell_y1 = cell_dy + cell_h + row_step * 0.1

        def _first_coord(d):
            m = re.search(r"[Mm]\s*([+-]?[\d.]+)[,\s]+([+-]?[\d.]+)", d)
            if m:
                return float(m.group(1)), float(m.group(2))
            return None, None

        # find the next <g> after this label
        for j in range(i + 1, min(i + 15, len(children))):
            c = children[j]
            if c.tag.split("}")[-1] == "g":
                segs = []
                for sub in c:
                    subtag = sub.tag.split("}")[-1]
                    if subtag == "path":
                        d = sub.get("d", "")
                        if d:
                            px, py = _first_coord(d)
                            if px is not None and not (
                                cell_x0 <= px <= cell_x1 and cell_y0 <= py <= cell_y1
                            ):
                                continue
                            segs.append(("path", d))
                    elif subtag == "rect":
                        rx = float(sub.get("x", 0))
                        ry = float(sub.get("y", 0))
                        rw = float(sub.get("width", 0))
                        rh = float(sub.get("height", 0))
                        # skip cell border rects (no fill, stroke only)
                        fill = sub.get("fill", "")
                        if fill == "none":
                            continue
                        segs.append(("rect", (rx, ry, rw, rh)))
                if segs:
                    glyphs[ch] = segs
                break

    return glyphs, char_grid


# ---------------------------------------------------------------------------
# Transform: SVG coords -> font units
# ---------------------------------------------------------------------------


def make_transform(col, row, config, scale, baseline_y):
    """
    Returns affine transform (sx, shy, shx, sy, dx, dy) that maps
    SVG pixel coords to font units with Y-flip.
    """
    grid = config["grid"]
    col_step = grid["cell_width"] + grid["col_gap"]
    row_step = grid["cell_height"] + grid["row_gap"] + grid["label_height"]
    margin_l = grid["margin_left"]
    margin_t = grid["margin_top"]
    label_h = grid["label_height"]

    baseline_svg = baseline_y + row * row_step
    cell_left_svg = margin_l + col * col_step

    sx = scale
    shy = 0.0
    shx = 0.0
    sy = -scale
    dx = -cell_left_svg * scale
    dy = baseline_svg * scale
    return (sx, shy, shx, sy, dx, dy)


# ---------------------------------------------------------------------------
# Build one TTF
# ---------------------------------------------------------------------------


def build_font(config, weight_cfg):
    """Build a single TTF from a filled glyph sheet SVG."""

    grid = config["grid"]
    sheets_dir = config.get("output", {}).get("sheets_dir", "sheets")
    fonts_dir = config.get("output", {}).get("fonts_dir", "fonts")
    os.makedirs(fonts_dir, exist_ok=True)

    svg_path = os.path.join(sheets_dir, weight_cfg["filename"])
    if not os.path.exists(svg_path):
        print(f"  ERROR: SVG not found: {svg_path}")
        return None

    font_type = config.get("font_type", "monospace")
    is_mono = font_type == "monospace"

    # read reference lines from SVG
    ref_positions = read_reference_lines(svg_path, config)

    required_refs = ["capline", "baseline"]
    for r in required_refs:
        if r not in ref_positions:
            print(f"  ERROR: Reference line '{r}' not found in {svg_path}")
            return None

    capline_y = ref_positions["capline"]
    baseline_y = ref_positions["baseline"]
    xheight_y = ref_positions.get("xheight", capline_y + (baseline_y - capline_y) * 0.4)
    descender_y = ref_positions.get(
        "descender", baseline_y + (baseline_y - capline_y) * 0.3
    )

    # derive metrics
    cap_span = baseline_y - capline_y
    if cap_span <= 0:
        print(
            f"  ERROR: Invalid reference lines (capline={capline_y}, baseline={baseline_y})"
        )
        return None

    overrides = weight_cfg.get("metrics_override", {})

    if overrides:
        capH = overrides["capH"]
        scale = capH / cap_span
        asc = overrides["asc"]
        desc = overrides["desc"]
        xH = overrides.get("xH", round((baseline_y - xheight_y) * scale))
        upm = asc + abs(desc)
    else:
        target_capH = 739
        scale = target_capH / cap_span

        capH = round((baseline_y - capline_y) * scale)

        margin_t = grid.get("margin_top", 0)
        label_h = grid.get("label_height", 0)
        cell_top_y = margin_t + label_h
        asc = round((baseline_y - cell_top_y) * scale)

        desc = -round((descender_y - baseline_y) * scale)
        xH = round((baseline_y - xheight_y) * scale)
        upm = asc + abs(desc)

    cell_w = grid["cell_width"]
    advance_w = round(cell_w * scale)

    family = config["family_name"]
    weight_name = weight_cfg["name"]
    style = weight_cfg["style"]
    ps_suffix = weight_cfg["ps_suffix"]
    weight_class = weight_cfg["weight_class"]

    full_name = f"{family} {weight_name}"
    ps_name = f"{family.replace(' ', '')}-{ps_suffix}"

    print(f"\n=== {full_name} ===")
    print(f"  UPM={upm}, asc={asc}, desc={desc}, capH={capH}, xH={xH}")
    print(f"  scale={scale:.4f}, advance_w={advance_w}")
    print(
        f"  ref lines: capline={capline_y}, xheight={xheight_y}, baseline={baseline_y}, descender={descender_y}"
    )

    # parse glyphs
    glyphs_data, char_grid = parse_svg(svg_path, config)
    print(f"  Glyphs parsed: {len(glyphs_data)}")

    all_chars = sorted(glyphs_data.keys(), key=lambda c: ord(c))
    glyph_order = [".notdef", "space"] + [f"uni{ord(c):04X}" for c in all_chars]

    cmap = {0x0020: "space"}
    for c in all_chars:
        cmap[ord(c)] = f"uni{ord(c):04X}"

    metrics = {}

    # .notdef — outlined rectangle
    pen = TTGlyphPen(None)
    m = round(advance_w * 0.06)
    im = round(advance_w * 0.18)
    pen.moveTo((m, desc))
    pen.lineTo((advance_w - m, desc))
    pen.lineTo((advance_w - m, asc))
    pen.lineTo((m, asc))
    pen.closePath()
    pen.moveTo((im, desc + im))
    pen.lineTo((im, asc - im))
    pen.lineTo((advance_w - im, asc - im))
    pen.lineTo((advance_w - im, desc + im))
    pen.closePath()
    tt_glyphs = {}
    tt_glyphs[".notdef"] = pen.glyph()
    metrics[".notdef"] = (advance_w, m)

    # space
    tt_glyphs["space"] = TTGlyphPen(None).glyph()
    metrics["space"] = (advance_w, 0)

    # for proportional fonts, pre-read all sidebearing markers
    sb_cache = {}
    if not is_mono:
        for ch, (col, row) in char_grid.items():
            sb_cache[ch] = read_sidebearing_markers(svg_path, config, col, row)

    class _FakeGlyf:
        pass

    errors = []
    for c in all_chars:
        gname = f"uni{ord(c):04X}"
        segs = glyphs_data[c]
        col, row = char_grid.get(c, (0, 0))
        xform = make_transform(col, row, config, scale, baseline_y)

        tt_pen = TTGlyphPen(None)
        cu2qu_pen = Cu2QuPen(tt_pen, max_err=1.0, reverse_direction=True)
        try:
            for kind, data in segs:
                if kind == "path":
                    draw_svg_path_to_pen(data, cu2qu_pen, transform=xform)
                elif kind == "rect":
                    draw_rect_to_pen(*data, cu2qu_pen, transform=xform)
            g = tt_pen.glyph()
            if g.numberOfContours != 0:
                g.recalcBounds(_FakeGlyf())
                lsb = g.xMin
            else:
                lsb = 0

            # determine advance width
            if is_mono:
                glyph_advance = advance_w
            else:
                lsb_x, rsb_x = sb_cache.get(c, (None, None))
                if lsb_x is not None and rsb_x is not None:
                    glyph_advance = round((rsb_x - lsb_x) * scale)
                else:
                    # fallback: use bounding box + default sidebearing
                    glyph_advance = advance_w

            tt_glyphs[gname] = g
            metrics[gname] = (glyph_advance, lsb)
        except Exception as e:
            errors.append((c, str(e)))
            tt_glyphs[gname] = TTGlyphPen(None).glyph()
            metrics[gname] = (advance_w, 0)

    if errors:
        print(f"  Errors on {len(errors)} glyphs: {[e[0] for e in errors]}")

    # assemble font
    fb = FontBuilder(upm, isTTF=True)
    fb.setupGlyphOrder(glyph_order)
    fb.setupCharacterMap(cmap)
    fb.setupGlyf(tt_glyphs)
    fb.setupHorizontalMetrics(metrics)
    fb.setupHorizontalHeader(ascent=asc, descent=desc)

    version = config.get("version", "1.0")
    copyright_str = config.get("copyright", "")
    trademark = config.get("trademark", "")
    vendor = config.get("vendor", "    ")[:4].ljust(4)
    designer = config.get("designer", "")
    description = config.get("description", "")
    url = config.get("url", "")

    fb.setupNameTable(
        {
            "copyright": copyright_str,
            "familyName": full_name,
            "styleName": style,
            "uniqueFontIdentifier": f"{version};{vendor.strip()};{ps_name}",
            "fullName": full_name,
            "version": f"Version {version}",
            "psName": ps_name,
            "trademark": trademark,
            "manufacturer": vendor.strip(),
            "designer": designer,
            "description": description,
            "vendorURL": url,
            "designerURL": url,
            "licenseDescription": copyright_str,
            "licenseInfoURL": url,
            "typographicFamily": family,
            "typographicSubfamily": style,
        }
    )

    # fsSelection: bit 7 = USE_TYPO_METRICS, bit 5 = Bold
    fs_sel = 0x80
    if style == "Bold":
        fs_sel |= 0x20

    panose = Panose()
    panose.bFamilyType = 2
    panose.bSerifStyle = 0
    panose.bWeight = max(2, min(9, weight_class // 100))
    panose.bProportion = 9 if is_mono else 0
    panose.bContrast = 0
    panose.bStrokeVariation = 0
    panose.bArmStyle = 0
    panose.bLetterForm = 0
    panose.bMidline = 0
    panose.bXHeight = 0

    mac_style = 0x01 if style == "Bold" else 0x00

    fb.setupOS2(
        version=4,
        sTypoAscender=asc,
        sTypoDescender=desc,
        sTypoLineGap=0,
        usWinAscent=asc,
        usWinDescent=abs(desc),
        sxHeight=xH,
        sCapHeight=capH,
        fsType=0,
        fsSelection=fs_sel,
        achVendID=vendor,
        usWeightClass=weight_class,
        panose=panose,
    )

    fb.setupHead(unitsPerEm=upm, macStyle=mac_style)
    fb.setupPost(isFixedPitch=1 if is_mono else 0)

    out_filename = f"{ps_name}.ttf"
    out_path = os.path.join(fonts_dir, out_filename)
    fb.font.save(out_path)
    print(f"  Saved: {out_path}")
    return out_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main():
    if len(sys.argv) >= 2:
        config_path = os.path.abspath(sys.argv[1])
    else:
        config_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "sheet_config.py"
        )

    weight_filter = sys.argv[2] if len(sys.argv) >= 3 else None

    config = load_config(config_path)

    for weight_cfg in config["weights"]:
        if weight_filter and weight_cfg["name"] != weight_filter:
            continue
        try:
            build_font(config, weight_cfg)
        except Exception as e:
            import traceback

            print(f"FAILED {weight_cfg['name']}: {e}")
            traceback.print_exc()

    print("\nDone.")


if __name__ == "__main__":
    main()
