#!/usr/bin/env python3
"""
GGWP — GlyphSheet Generation Workflow Protocol
Generate blank glyph sheet SVGs from a config file.

Usage:
    python3 generate_sheet.py                    # uses sheet_config.py
    python3 generate_sheet.py my_config.py       # uses custom config
    python3 generate_sheet.py my_config.py Book  # generate only Book weight

The config file must define a CONFIG dict. See sheet_config.py for format.
"""

import sys
import os
import math
import importlib.util


def load_config(config_path):
    """Load CONFIG dict from a Python file."""
    spec = importlib.util.spec_from_file_location("config_module", config_path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    if not hasattr(mod, "CONFIG"):
        raise ValueError(f"{config_path} does not define a CONFIG dict")
    return mod.CONFIG


def _escape_xml(text):
    """Escape special characters for SVG/XML text content."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("'", "&apos;")
    )


def _char_label(ch):
    """Human-readable label for a character in the glyph sheet."""
    cp = ord(ch)
    # Show printable ASCII as the character itself, others as U+XXXX
    if 0x21 <= cp <= 0x7E:
        return _escape_xml(ch)
    return f"U+{cp:04X}"


def generate_sheet(config, weight_cfg):
    """Generate one blank glyph sheet SVG for a given weight."""

    grid = config["grid"]
    refs = config["reference_lines"]
    appear = config["appearance"]
    codepoints = config["codepoints"]
    font_type = config.get("font_type", "monospace")
    sb_markers = config.get("sidebearing_markers", {})

    columns = grid["columns"]
    cell_w = grid["cell_width"]
    cell_h = grid["cell_height"]
    col_gap = grid["col_gap"]
    row_gap = grid["row_gap"]
    label_h = grid["label_height"]
    margin_l = grid["margin_left"]
    margin_t = grid["margin_top"]
    margin_r = grid["margin_right"]
    margin_b = grid["margin_bottom"]

    col_step = cell_w + col_gap
    row_step = cell_h + row_gap + label_h

    rows = math.ceil(len(codepoints) / columns)

    svg_w = margin_l + columns * col_step - col_gap + margin_r
    svg_h = margin_t + rows * row_step - row_gap + margin_b

    lines = []
    lines.append(
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{svg_w}" height="{svg_h}" '
        f'viewBox="0 0 {svg_w} {svg_h}">'
    )

    # -- metadata comment --
    lines.append(
        f"  <!-- GGWP Glyph Sheet: {config['family_name']} {weight_cfg['name']} -->"
    )
    lines.append(f"  <!-- Font type: {font_type} -->")
    lines.append(
        f"  <!-- Grid: {columns} columns x {rows} rows, cell {cell_w}x{cell_h}px -->"
    )
    lines.append(f"  <!-- Generated by generate_sheet.py -->")

    # -- background --
    bg = appear["background"]
    lines.append(f'  <rect width="{svg_w}" height="{svg_h}" fill="{bg}"/>')

    # -- title --
    title = f"{config['family_name']} {weight_cfg['name']}"
    lines.append(
        f'  <text x="{margin_l}" y="{margin_t - 20}" '
        f'fill="{appear["label_color"]}" '
        f'font-family="monospace" font-size="14">'
        f"{_escape_xml(title)}</text>"
    )

    # -- reference line legend (top-right) --
    legend_x = svg_w - margin_r - 200
    legend_y = margin_t - 35
    for i, (key, ref) in enumerate(refs.items()):
        lx = legend_x + i * 50
        lines.append(
            f'  <line x1="{lx}" y1="{legend_y}" '
            f'x2="{lx + 20}" y2="{legend_y}" '
            f'stroke="{ref["color"]}" stroke-width="1" '
            f'opacity="0.8"/>'
        )
        lines.append(
            f'  <text x="{lx + 22}" y="{legend_y + 3}" '
            f'fill="{appear["label_color"]}" '
            f'font-family="monospace" font-size="5">'
            f"{key}</text>"
        )

    # -- cells --
    for idx, ch in enumerate(codepoints):
        col = idx % columns
        row = idx // columns

        # cell origin (top-left of label area)
        cx = margin_l + col * col_step
        cy = margin_t + row * row_step

        # label position (above drawing area)
        label_x = cx + 2
        label_y = cy + label_h - 3
        label_text = _char_label(ch)
        cp_hex = f"U+{ord(ch):04X}"

        lines.append(f"  <!-- Cell [{col},{row}] {cp_hex} -->")

        # codepoint label
        lines.append(
            f'  <text x="{label_x}" y="{label_y}" '
            f'fill="{appear["label_color"]}" '
            f'font-family="monospace" '
            f'font-size="{appear["label_font_size"]}px" '
            f'style="font-size:{appear["label_font_size"]}px">'
            f"{label_text}</text>"
        )

        # drawing area origin
        dx = cx
        dy = cy + label_h

        # reference lines (horizontal, spanning cell_width)
        ref_opacity = appear["ref_line_opacity"]
        ref_lw = appear["ref_line_width"]
        for key, ref in refs.items():
            ry = dy + ref["y"]
            # clamp to cell bounds
            if ref["y"] < 0 or ref["y"] > cell_h:
                continue
            lines.append(
                f'  <line x1="{dx}" y1="{ry}" '
                f'x2="{dx + cell_w}" y2="{ry}" '
                f'stroke="{ref["color"]}" '
                f'stroke-width="{ref_lw}" '
                f'opacity="{ref_opacity}"/>'
            )

        # LSB/RSB markers for proportional fonts
        if font_type == "proportional":
            mk_opacity = appear.get("marker_opacity", 0.6)
            mk_lw = appear.get("marker_line_width", 0.5)
            lsb_color = sb_markers.get("lsb_color", "#00FFFF")
            rsb_color = sb_markers.get("rsb_color", "#FF00FF")

            # default LSB at ~10% from left, RSB at ~90% from left
            lsb_x = dx + round(cell_w * 0.1)
            rsb_x = dx + round(cell_w * 0.9)

            lines.append(
                f'  <line x1="{lsb_x}" y1="{dy}" '
                f'x2="{lsb_x}" y2="{dy + cell_h}" '
                f'stroke="{lsb_color}" '
                f'stroke-width="{mk_lw}" '
                f'opacity="{mk_opacity}"/>'
            )
            lines.append(
                f'  <line x1="{rsb_x}" y1="{dy}" '
                f'x2="{rsb_x}" y2="{dy + cell_h}" '
                f'stroke="{rsb_color}" '
                f'stroke-width="{mk_lw}" '
                f'opacity="{mk_opacity}"/>'
            )

        # placeholder <g> for glyph paths (designer draws here)
        lines.append(f'  <g id="glyph-{cp_hex}">')
        lines.append(f"  </g>")

        # cell border rectangle (drawing area only)
        lines.append(
            f'  <rect x="{dx}" y="{dy}" '
            f'width="{cell_w}" height="{cell_h}" '
            f'fill="none" '
            f'stroke="{appear["cell_border_color"]}" '
            f'stroke-width="{appear["cell_border_width"]}"/>'
        )

    lines.append("</svg>")

    return "\n".join(lines)


def main():
    # determine config path
    if len(sys.argv) >= 2:
        config_path = os.path.abspath(sys.argv[1])
    else:
        config_path = os.path.join(
            os.path.dirname(os.path.abspath(__file__)), "sheet_config.py"
        )

    # optional: filter to a single weight
    weight_filter = sys.argv[2] if len(sys.argv) >= 3 else None

    config = load_config(config_path)

    sheets_dir = config.get("output", {}).get("sheets_dir", "sheets")
    os.makedirs(sheets_dir, exist_ok=True)

    for weight_cfg in config["weights"]:
        if weight_filter and weight_cfg["name"] != weight_filter:
            continue

        svg_content = generate_sheet(config, weight_cfg)
        out_path = os.path.join(sheets_dir, weight_cfg["filename"])
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(svg_content)

        n_glyphs = len(config["codepoints"])
        cols = config["grid"]["columns"]
        rows = math.ceil(n_glyphs / cols)
        print(f"Generated: {out_path} ({n_glyphs} glyphs, {cols}x{rows} grid)")

    print("Done.")


if __name__ == "__main__":
    main()
